bracketSpacing: true
endOfLine: "auto"
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false

overrides:
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["importAssertions", "typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
