plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "@semantic-release/npm"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: dev/*
    prerelease: "beta"
  - name: develop/*
    prerelease: 'beta'
  - name: hotfix/*
    prerelease: '${name.replace(/^hotfix\//g, "fix-").replace(/\//g, "-")}'
  - name: fix/*
    prerelease: '${name.replace(/^fix\//g, "fix-").replace(/\//g, "-")}'
  - name: feat/init
    prerelease: 'beta'
