/**
 * RecordOperationsImpl - Low-level record CRUD operations.
 *
 * This module provides the implementation for direct AT Protocol
 * record operations (create, read, update, delete, list).
 *
 * @packageDocumentation
 */

import type { Agent } from "@atproto/api";
import { NetworkError, ValidationError } from "../errors.js";
import type { RecordOperations } from "./interfaces.js";
import type { CreateResult, UpdateResult, PaginatedList } from "./types.js";
import type { LexiconRegistry } from "./LexiconRegistry.js";

/**
 * Implementation of low-level AT Protocol record operations.
 *
 * This class provides direct access to the AT Protocol repository API
 * for CRUD operations on records. It handles:
 *
 * - Lexicon validation before create/update operations
 * - Error mapping to SDK error types
 * - Response normalization
 *
 * @remarks
 * This class is typically not instantiated directly. Access it through
 * {@link Repository.records}.
 *
 * All operations are performed against the repository DID specified
 * at construction time. To operate on a different repository, create
 * a new Repository instance using {@link Repository.repo}.
 *
 * @example
 * ```typescript
 * // Access through Repository
 * const repo = sdk.repository(session);
 *
 * // Create a record
 * const { uri, cid } = await repo.records.create({
 *   collection: "org.example.myRecord",
 *   record: { title: "Hello", createdAt: new Date().toISOString() },
 * });
 *
 * // Update the record
 * const rkey = uri.split("/").pop()!;
 * await repo.records.update({
 *   collection: "org.example.myRecord",
 *   rkey,
 *   record: { title: "Updated", createdAt: new Date().toISOString() },
 * });
 * ```
 *
 * @internal
 */
export class RecordOperationsImpl implements RecordOperations {
  /**
   * Creates a new RecordOperationsImpl.
   *
   * @param agent - AT Protocol Agent for making API calls
   * @param repoDid - DID of the repository to operate on
   * @param lexiconRegistry - Optional registry for validating records against lexicon schemas
   *
   * @internal
   */
  constructor(
    private agent: Agent,
    private repoDid: string,
    private lexiconRegistry?: LexiconRegistry,
  ) {}

  /**
   * Creates a new record in the specified collection.
   *
   * @param params - Creation parameters
   * @param params.collection - NSID of the collection (e.g., "org.hypercerts.hypercert")
   * @param params.record - Record data conforming to the collection's lexicon schema
   * @param params.rkey - Optional record key. If not provided, a TID (timestamp-based ID)
   *                      is automatically generated by the server.
   * @param params.skipValidation - Optional flag to skip lexicon validation (default: false)
   * @returns Promise resolving to the created record's URI and CID
   * @throws {@link ValidationError} if the record doesn't conform to the lexicon schema
   * @throws {@link NetworkError} if the API request fails
   *
   * @remarks
   * The record is validated against the collection's lexicon before sending
   * to the server if the collection is registered in the LexiconRegistry.
   * If no lexicon is registered for the collection, validation is skipped
   * (allowing custom record types). Use `skipValidation: true` to bypass
   * validation even for registered collections.
   *
   * **AT-URI Format**: `at://{did}/{collection}/{rkey}`
   *
   * @example
   * ```typescript
   * const result = await repo.records.create({
   *   collection: "org.hypercerts.hypercert",
   *   record: {
   *     title: "My Hypercert",
   *     description: "...",
   *     createdAt: new Date().toISOString(),
   *   },
   * });
   * console.log(`Created: ${result.uri}`);
   * // Output: Created: at://did:plc:abc123/org.hypercerts.hypercert/xyz789
   * ```
   */
  async create(params: {
    collection: string;
    record: unknown;
    rkey?: string;
    skipValidation?: boolean;
  }): Promise<CreateResult> {
    try {
      // Validate record against registered lexicon if available
      if (!params.skipValidation && this.lexiconRegistry?.isRegistered(params.collection)) {
        const validation = this.lexiconRegistry.validate(params.collection, params.record);
        if (!validation.valid) {
          throw new ValidationError(`Invalid record for collection ${params.collection}: ${validation.error}`);
        }
      }

      const result = await this.agent.com.atproto.repo.createRecord({
        repo: this.repoDid,
        collection: params.collection,
        record: params.record as Record<string, unknown>,
        rkey: params.rkey,
      });

      if (!result.success) {
        throw new NetworkError("Failed to create record");
      }

      return { uri: result.data.uri, cid: result.data.cid };
    } catch (error) {
      if (error instanceof ValidationError || error instanceof NetworkError) throw error;
      throw new NetworkError(
        `Failed to create record: ${error instanceof Error ? error.message : "Unknown error"}`,
        error,
      );
    }
  }

  /**
   * Updates an existing record (full replacement).
   *
   * @param params - Update parameters
   * @param params.collection - NSID of the collection
   * @param params.rkey - Record key (the last segment of the AT-URI)
   * @param params.record - New record data (completely replaces existing record)
   * @param params.skipValidation - Optional flag to skip lexicon validation (default: false)
   * @returns Promise resolving to the updated record's URI and new CID
   * @throws {@link ValidationError} if the record doesn't conform to the lexicon schema
   * @throws {@link NetworkError} if the API request fails
   *
   * @remarks
   * This is a full replacement operation, not a partial update. The entire
   * record is replaced with the new data. To preserve existing fields,
   * first fetch the record with {@link get}, modify it, then update.
   *
   * The record is validated against the collection's lexicon before sending
   * to the server if the collection is registered in the LexiconRegistry.
   * Use `skipValidation: true` to bypass validation.
   *
   * @example
   * ```typescript
   * // Get existing record
   * const existing = await repo.records.get({
   *   collection: "org.hypercerts.hypercert",
   *   rkey: "xyz789",
   * });
   *
   * // Update with modified data
   * const updated = await repo.records.update({
   *   collection: "org.hypercerts.hypercert",
   *   rkey: "xyz789",
   *   record: {
   *     ...existing.value,
   *     title: "Updated Title",
   *   },
   * });
   * ```
   */
  async update(params: {
    collection: string;
    rkey: string;
    record: unknown;
    skipValidation?: boolean;
  }): Promise<UpdateResult> {
    try {
      // Validate record against registered lexicon if available
      if (!params.skipValidation && this.lexiconRegistry?.isRegistered(params.collection)) {
        const validation = this.lexiconRegistry.validate(params.collection, params.record);
        if (!validation.valid) {
          throw new ValidationError(`Invalid record for collection ${params.collection}: ${validation.error}`);
        }
      }

      const result = await this.agent.com.atproto.repo.putRecord({
        repo: this.repoDid,
        collection: params.collection,
        rkey: params.rkey,
        record: params.record as Record<string, unknown>,
      });

      if (!result.success) {
        throw new NetworkError("Failed to update record");
      }

      return { uri: result.data.uri, cid: result.data.cid };
    } catch (error) {
      if (error instanceof ValidationError || error instanceof NetworkError) throw error;
      throw new NetworkError(
        `Failed to update record: ${error instanceof Error ? error.message : "Unknown error"}`,
        error,
      );
    }
  }

  /**
   * Gets a single record by collection and key.
   *
   * @param params - Get parameters
   * @param params.collection - NSID of the collection
   * @param params.rkey - Record key
   * @returns Promise resolving to the record's URI, CID, and value
   * @throws {@link NetworkError} if the record is not found or request fails
   *
   * @example
   * ```typescript
   * const record = await repo.records.get({
   *   collection: "org.hypercerts.hypercert",
   *   rkey: "xyz789",
   * });
   *
   * console.log(record.uri);    // at://did:plc:abc123/org.hypercerts.hypercert/xyz789
   * console.log(record.cid);    // bafyrei...
   * console.log(record.value);  // { title: "...", description: "...", ... }
   * ```
   */
  async get(params: { collection: string; rkey: string }): Promise<{ uri: string; cid: string; value: unknown }> {
    try {
      const result = await this.agent.com.atproto.repo.getRecord({
        repo: this.repoDid,
        collection: params.collection,
        rkey: params.rkey,
      });

      if (!result.success) {
        throw new NetworkError("Failed to get record");
      }

      return { uri: result.data.uri, cid: result.data.cid ?? "", value: result.data.value };
    } catch (error) {
      if (error instanceof NetworkError) throw error;
      throw new NetworkError(
        `Failed to get record: ${error instanceof Error ? error.message : "Unknown error"}`,
        error,
      );
    }
  }

  /**
   * Lists records in a collection with pagination.
   *
   * @param params - List parameters
   * @param params.collection - NSID of the collection
   * @param params.limit - Maximum number of records to return (server may impose its own limit)
   * @param params.cursor - Pagination cursor from a previous response
   * @returns Promise resolving to paginated list of records
   * @throws {@link NetworkError} if the request fails
   *
   * @remarks
   * Records are returned in reverse chronological order (newest first).
   * Use the `cursor` from the response to fetch subsequent pages.
   *
   * @example Paginating through all records
   * ```typescript
   * let cursor: string | undefined;
   * const allRecords = [];
   *
   * do {
   *   const page = await repo.records.list({
   *     collection: "org.hypercerts.hypercert",
   *     limit: 100,
   *     cursor,
   *   });
   *   allRecords.push(...page.records);
   *   cursor = page.cursor;
   * } while (cursor);
   *
   * console.log(`Total records: ${allRecords.length}`);
   * ```
   */
  async list(params: {
    collection: string;
    limit?: number;
    cursor?: string;
  }): Promise<PaginatedList<{ uri: string; cid: string; value: unknown }>> {
    try {
      const result = await this.agent.com.atproto.repo.listRecords({
        repo: this.repoDid,
        collection: params.collection,
        limit: params.limit,
        cursor: params.cursor,
      });

      if (!result.success) {
        throw new NetworkError("Failed to list records");
      }

      return {
        records: result.data.records?.map((r) => ({ uri: r.uri, cid: r.cid, value: r.value })) || [],
        cursor: result.data.cursor ?? undefined,
      };
    } catch (error) {
      if (error instanceof NetworkError) throw error;
      throw new NetworkError(
        `Failed to list records: ${error instanceof Error ? error.message : "Unknown error"}`,
        error,
      );
    }
  }

  /**
   * Deletes a record from a collection.
   *
   * @param params - Delete parameters
   * @param params.collection - NSID of the collection
   * @param params.rkey - Record key to delete
   * @throws {@link NetworkError} if the deletion fails
   *
   * @remarks
   * Deletion is permanent. The record's AT-URI cannot be reused (the same
   * rkey can be used for a new record, but it will have a different CID).
   *
   * @example
   * ```typescript
   * await repo.records.delete({
   *   collection: "org.hypercerts.hypercert",
   *   rkey: "xyz789",
   * });
   * ```
   */
  async delete(params: { collection: string; rkey: string }): Promise<void> {
    try {
      const result = await this.agent.com.atproto.repo.deleteRecord({
        repo: this.repoDid,
        collection: params.collection,
        rkey: params.rkey,
      });

      if (!result.success) {
        throw new NetworkError("Failed to delete record");
      }
    } catch (error) {
      if (error instanceof NetworkError) throw error;
      throw new NetworkError(
        `Failed to delete record: ${error instanceof Error ? error.message : "Unknown error"}`,
        error,
      );
    }
  }
}
