/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Hypercerts API
 * API for uploading allow lists and hypercert metadata. Visit /graphql for the GraphQL API.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type DeleteBlueprint200AnyOfSix = {
  data?: unknown;
  errors?: unknown;
  message: string;
  success: boolean;
};

export type DeleteBlueprint200AnyOfFourErrors = {
  blueprint?: unknown;
  signature: string;
};

export type DeleteBlueprint200AnyOfFour = {
  data?: unknown;
  errors: DeleteBlueprint200AnyOfFourErrors;
  message: string;
  success: boolean;
};

export type DeleteBlueprint200AnyOfTwoErrors = {
  blueprint: string;
  signature?: unknown;
};

export type DeleteBlueprint200AnyOfTwo = {
  data?: unknown;
  errors: DeleteBlueprint200AnyOfTwoErrors;
  message: string;
  success: boolean;
};

export type DeleteBlueprint200AnyOf = {
  data: unknown;
  errors: unknown;
  message: string;
  success: boolean;
};

export type DeleteBlueprint200 = DeleteBlueprint200AnyOf | DeleteBlueprint200AnyOfTwo | DeleteBlueprint200AnyOfFour | DeleteBlueprint200AnyOfSix;

export type DeleteHyperboardParams = {
adminAddress: string;
signature: string;
};

export type ValidateOrder200 = {
  data: unknown[];
  message: string;
  success: boolean;
};

export type UpdateOrderNonce200Data = {
  nonce_counter: number;
};

export type UpdateOrderNonce200 = {
  data: UpdateOrderNonce200Data;
  message: string;
  success: boolean;
};

export type DeleteOrder200 = {
  data: unknown;
  message: string;
  success: boolean;
};

export type DeleteOrderBody = {
  orderId: string;
  signature: string;
};

export type StoreOrder201AnyOf = {
  error: string;
  message: string;
  result?: RecordStringUnknown;
  success: boolean;
};

export type StoreOrder201 = BaseResponse | StoreOrder201AnyOf;

export type StoreMetadata201AnyOfFourErrors = {
  metadata: string;
};

export type StoreMetadata201AnyOfFour = {
  data?: unknown;
  errors: StoreMetadata201AnyOfFourErrors;
  message: string;
  success: boolean;
  valid?: unknown;
};

export type StoreMetadata201AnyOfTwoData = {
  cid: string;
};

export type StoreMetadata201AnyOfTwo = {
  data: StoreMetadata201AnyOfTwoData;
  errors?: unknown;
  message?: unknown;
  success: boolean;
  valid?: unknown;
};

export type StoreMetadata201AnyOf = {
  data?: unknown;
  errors: RecordStringStringOrStringArray;
  message: string;
  success: boolean;
  valid: boolean;
};

export type StoreMetadata201 = StoreMetadata201AnyOf | StoreMetadata201AnyOfTwo | StoreMetadata201AnyOfFour;

export type HealthCheck200 = {
  memory: ProcessNodeJSMemoryUsage;
  status: string;
  timestamp: number;
  uptime: number;
};

export type ProcessSignatureRequests200 = {
  message: string;
  success: boolean;
};

export type CancelSignatureRequest200 = {
  message: string;
  success: boolean;
};

export type UploadBody = {
  /** - Array of files to upload (max 5 files, 10MB each) */
  files?: Blob[];
  /** - Optional JSON string with additional metadata */
  jsonData?: string;
};

export interface ValidateAllowListRequest {
  allowList: string;
  totalUnits?: string;
}

export interface StoreAllowListRequest {
  allowList: string;
  totalUnits?: string;
}

export interface BlueprintQueueMintRequest {
  chain_id: number;
  minter_address: string;
  signature: string;
  tx_hash: string;
}

export interface BlueprintDeleteRequest {
  admin_address: string;
  chain_id: number;
  signature: string;
}

export interface BlueprintCreateRequest {
  admin_address: string;
  chain_id: number;
  form_values: unknown;
  minter_address: string;
  signature: string;
}

export type BlueprintResponseData = {
  blueprint_id: number;
};

export interface BlueprintResponse {
  data?: BlueprintResponseData;
  errors?: RecordStringUnknown;
  message?: string;
  success: boolean;
}

export type HyperboardUpdateRequestCollectionsItemHypercertsItem = {
  factor: number;
  hypercertId: string;
};

export type HyperboardUpdateRequestCollectionsItemBlueprintsItem = {
  blueprintId: number;
  factor: number;
};

export type HyperboardUpdateRequestCollectionsItem = {
  blueprints: HyperboardUpdateRequestCollectionsItemBlueprintsItem[];
  description: string;
  hypercerts: HyperboardUpdateRequestCollectionsItemHypercertsItem[];
  id?: string;
  title: string;
};

export interface HyperboardUpdateRequest {
  adminAddress: string;
  backgroundImg?: string;
  borderColor: string;
  chainIds: number[];
  collections: HyperboardUpdateRequestCollectionsItem[];
  id: string;
  signature: string;
  title: string;
}

export interface HyperboardCreateRequest {
  adminAddress: string;
  backgroundImg?: string;
  borderColor: string;
  chainIds: number[];
  collections: HyperboardCreateRequestCollectionsItem[];
  signature: string;
  title: string;
}

export type HyperboardCreateRequestCollectionsItemHypercertsItem = {
  factor: number;
  hypercertId: string;
};

export type HyperboardCreateRequestCollectionsItemBlueprintsItem = {
  blueprintId: number;
  factor: number;
};

export type HyperboardCreateRequestCollectionsItem = {
  blueprints: HyperboardCreateRequestCollectionsItemBlueprintsItem[];
  description: string;
  hypercerts: HyperboardCreateRequestCollectionsItemHypercertsItem[];
  id?: string;
  title: string;
};

export type HyperboardResponseData = {
  id: string;
};

export interface HyperboardResponse {
  data?: HyperboardResponseData;
  errors?: RecordStringUnknown;
  message?: string;
  success: boolean;
}

export interface ValidateOrderRequest {
  chainId: number;
  tokenIds: string[];
}

export interface UpdateOrderNonceRequest {
  address: string;
  chainId: number;
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickEOACreateOrderRequestExcludeKeyofEOACreateOrderRequestType {
  additionalParameters: string;
  amounts: number[];
  chainId: number;
  collection: string;
  collectionType: number;
  currency: string;
  endTime: number;
  globalNonce: string;
  itemIds: string[];
  orderNonce: string;
  price: string;
  quoteType: number;
  signature: string;
  signer: string;
  startTime: number;
  strategyId: number;
  subsetNonce: number;
}

export type CreateOrderRequest = EOACreateOrderRequest | MultisigCreateOrderRequest | PickEOACreateOrderRequestExcludeKeyofEOACreateOrderRequestType;

export type LegacyCreateOrderRequest = PickEOACreateOrderRequestExcludeKeyofEOACreateOrderRequestType;

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitEOACreateOrderRequestType = PickEOACreateOrderRequestExcludeKeyofEOACreateOrderRequestType;

/**
 */
export type MultisigCreateOrderRequestType = typeof MultisigCreateOrderRequestType[keyof typeof MultisigCreateOrderRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MultisigCreateOrderRequestType = {
  multisig: 'multisig',
} as const;

export interface MultisigCreateOrderRequest {
  chainId: number;
  messageHash: string;
  /** */
  type: MultisigCreateOrderRequestType;
}

/**
 */
export type EOACreateOrderRequestType = typeof EOACreateOrderRequestType[keyof typeof EOACreateOrderRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EOACreateOrderRequestType = {
  eoa: 'eoa',
} as const;

export interface EOACreateOrderRequest {
  additionalParameters: string;
  amounts: number[];
  chainId: number;
  collection: string;
  collectionType: number;
  currency: string;
  endTime: number;
  globalNonce: string;
  itemIds: string[];
  orderNonce: string;
  price: string;
  quoteType: number;
  signature: string;
  signer: string;
  startTime: number;
  strategyId: number;
  subsetNonce: number;
  /** */
  type: EOACreateOrderRequestType;
}

export interface ValidateMetadataRequest {
  metadata: HypercertMetadata;
}

export interface ValidationResponse {
  data?: unknown;
  errors?: RecordStringUnknown;
  message?: string;
  success: boolean;
  valid: boolean;
}

export type StorageResponseData = {
  cid: string;
};

export interface StorageResponse {
  data?: StorageResponseData;
  errors?: RecordStringUnknown;
  message?: string;
  success: boolean;
}

/**
 * Claim data for hypercert. ERC1155 Metadata compliant
 */
export interface HypercertMetadata {
  /** A CID pointer to the merke tree proof json on ipfs */
  allowList?: string;
  /** Describes the asset to which this token represents */
  description: string;
  /** An url pointing to the external website of the project */
  external_url?: string;
  hypercert?: HypercertClaimdata;
  /** A URI pointing to a resource with mime type image/* representing the asset to which this token represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive. */
  image: string;
  /** Identifies the asset to which this token represents */
  name: string;
  properties?: HypercertMetadataPropertiesItem[];
  /** Describes the asset to which this token represents */
  ref?: string;
  /** The version of Hypercert schema used to describe this hypercert */
  version?: string;
}

export interface StoreMetadataWithAllowlistRequest {
  allowList: string;
  metadata: HypercertMetadata;
  totalUnits?: string;
}

export interface StoreMetadataRequest {
  metadata: HypercertMetadata;
}

export type HypercertMetadataPropertiesItemAnyOfTwo = {
  name: string;
  src: string;
  trait_type: string;
  type: string;
};

export type HypercertMetadataPropertiesItemAnyOf = {
  trait_type: string;
  value: string;
};

export type HypercertMetadataPropertiesItem = HypercertMetadataPropertiesItemAnyOf | HypercertMetadataPropertiesItemAnyOfTwo;

/**
 * Work time period. The value is UNIX time in seconds from epoch.
 */
export type HypercertClaimdataWorkTimeframe = {
  display_value?: string;
  name?: string;
  value?: number[];
  [key: string]: unknown;
};

/**
 * Scopes of work
 */
export type HypercertClaimdataWorkScope = {
  display_value?: string;
  excludes?: string[];
  name?: string;
  value?: string[];
  [key: string]: unknown;
};

/**
 * Rights
 */
export type HypercertClaimdataRights = {
  display_value?: string;
  excludes?: string[];
  name?: string;
  value?: string[];
  [key: string]: unknown;
};

/**
 * Impact time period. The value is UNIX time in seconds from epoch.
 */
export type HypercertClaimdataImpactTimeframe = {
  display_value?: string;
  name?: string;
  value?: number[];
  [key: string]: unknown;
};

/**
 * Scopes of impact
 */
export type HypercertClaimdataImpactScope = {
  display_value?: string;
  excludes?: string[];
  name?: string;
  value?: string[];
  [key: string]: unknown;
};

/**
 * Contributors
 */
export type HypercertClaimdataContributors = {
  display_value?: string;
  name?: string;
  value?: string[];
  [key: string]: unknown;
};

/**
 * Properties of an impact claim
 */
export interface HypercertClaimdata {
  /** Contributors */
  contributors: HypercertClaimdataContributors;
  /** Scopes of impact */
  impact_scope: HypercertClaimdataImpactScope;
  /** Impact time period. The value is UNIX time in seconds from epoch. */
  impact_timeframe: HypercertClaimdataImpactTimeframe;
  /** Rights */
  rights?: HypercertClaimdataRights;
  /** Scopes of work */
  work_scope: HypercertClaimdataWorkScope;
  /** Work time period. The value is UNIX time in seconds from epoch. */
  work_timeframe: HypercertClaimdataWorkTimeframe;
  [key: string]: unknown;
}

/**
 * Construct a type with a set of properties K of type T
 */
export interface RecordStringStringOrStringArray { [key: string]: unknown }

export interface ProcessNodeJSMemoryUsage {
  arrayBuffers: number;
  external: number;
  heapTotal: number;
  heapUsed: number;
  rss: number;
}

export interface CancelSignatureRequest {
  chain_id: number;
  owner_address: string;
  signature: string;
}

export type UploadResponseDataResultsItem = {
  cid: string;
  fileName: string;
};

export type UploadResponseDataFailedItem = {
  error: string;
  fileName: string;
};

export type UploadResponseData = {
  failed: UploadResponseDataFailedItem[];
  results: UploadResponseDataResultsItem[];
};

/**
 * Construct a type with a set of properties K of type T
 */
export interface RecordStringString {[key: string]: string}

export type UploadStatus = typeof UploadStatus[keyof typeof UploadStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadStatus = {
  all: 'all',
  some: 'some',
  none: 'none',
} as const;

export interface UploadResponse {
  data?: UploadResponseData;
  errors?: RecordStringString;
  message: string;
  success: boolean;
  uploadStatus: UploadStatus;
}

/**
 */
export type MultisigUserUpsertRequestType = typeof MultisigUserUpsertRequestType[keyof typeof MultisigUserUpsertRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MultisigUserUpsertRequestType = {
  multisig: 'multisig',
} as const;

export interface MultisigUserUpsertRequest {
  chain_id: number;
  messageHash: string;
  /** */
  type: MultisigUserUpsertRequestType;
}

export type AddOrUpdateUserRequest = EOAUserUpsertRequest | MultisigUserUpsertRequest;

/**
 */
export type EOAUserUpsertRequestType = typeof EOAUserUpsertRequestType[keyof typeof EOAUserUpsertRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EOAUserUpsertRequestType = {
  eoa: 'eoa',
} as const;

export interface EOAUserUpsertRequest {
  avatar?: string;
  chain_id: number;
  display_name?: string;
  signature: string;
  /** */
  type: EOAUserUpsertRequestType;
}

export type UserResponseData = {
  address: string;
};

/**
 * Construct a type with a set of properties K of type T
 */
export interface RecordStringUnknown {[key: string]: unknown}

export interface BaseResponse {
  errors?: RecordStringUnknown;
  message?: string;
  success: boolean;
}

export interface UserResponse {
  data?: UserResponseData;
  errors?: RecordStringUnknown;
  message?: string;
  success: boolean;
}





  /**
 * Add or update a user
 */
export const addOrUpdateUser = <TData = AxiosResponse<UserResponse>>(
    address: string,
    addOrUpdateUserRequest: AddOrUpdateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/users/${address}`,
      addOrUpdateUserRequest,options
    );
  }

/**
 * Upload one or more files to IPFS storage.
 * @summary Upload files to IPFS
 */
export const upload = <TData = AxiosResponse<UploadResponse>>(
    uploadBody?: UploadBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
if(uploadBody?.files !== undefined) {
 uploadBody.files.forEach(value => formData.append('files', value));
 }
if(uploadBody?.jsonData !== undefined) {
 formData.append('jsonData', uploadBody.jsonData)
 }

    return axios.post(
      `/v2/upload`,
      formData,options
    );
  }

export const cancelSignatureRequest = <TData = AxiosResponse<CancelSignatureRequest200>>(
    safeAddress: string,
    messageHash: string,
    cancelSignatureRequest: CancelSignatureRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/signature-requests/${safeAddress}-${messageHash}/cancel`,
      cancelSignatureRequest,options
    );
  }

export const processSignatureRequests = <TData = AxiosResponse<ProcessSignatureRequests200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/signature-requests/process`,undefined,options
    );
  }

export const healthCheck = <TData = AxiosResponse<HealthCheck200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v2/monitoring/health`,options
    );
  }

/**
 * Submits a new hypercert metadata object for validation and storage on IPFS.
When an allowlist URI is provided the service will validate the allowlist data before storing the metadata.
Note that this might lead to a race condition when uploading metadata and the allowlist separately in rapid succession.
In that case we recommend using POST /metadata/with-allowlist instead.
 */
export const storeMetadata = <TData = AxiosResponse<StoreMetadata201>>(
    storeMetadataRequest: StoreMetadataRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/metadata`,
      storeMetadataRequest,options
    );
  }

/**
 * Submits a new hypercert metadata object paired with allowlist data for validation and storage on IPFS.
The service will parse and validate the allow list data and the metadata.
After successful validation, the allow list data will be uploaded to IPFS and the URI of the allowlist will be attached to the hypercert metadata.
If an allow list URI is already present, the service will return an error.
 */
export const storeMetadataWithAllowlist = <TData = AxiosResponse<StorageResponse>>(
    storeMetadataWithAllowlistRequest: StoreMetadataWithAllowlistRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/metadata/with-allowlist`,
      storeMetadataWithAllowlistRequest,options
    );
  }

/**
 * Validates a hypercert metadata object. When an allowlist URI is provided the service will validate the allowlist data as well.
 */
export const validateMetadata = <TData = AxiosResponse<ValidationResponse>>(
    validateMetadataRequest: ValidateMetadataRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/metadata/validate`,
      validateMetadataRequest,options
    );
  }

/**
 * Validates a hypercert metadata object paired with allowlist data.
 */
export const validateMetadataWithAllowlist = <TData = AxiosResponse<ValidationResponse>>(
    storeMetadataWithAllowlistRequest: StoreMetadataWithAllowlistRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/metadata/with-allowlist/validate`,
      storeMetadataWithAllowlistRequest,options
    );
  }

/**
 * Submits a new order for validation and storage on the database.

For backwards compatibility, the old v1 order format is also supported. (Example 3)
 */
export const storeOrder = <TData = AxiosResponse<StoreOrder201>>(
    createOrderRequest: CreateOrderRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/marketplace/orders`,
      createOrderRequest,options
    );
  }

/**
 * Delete order from database
 */
export const deleteOrder = <TData = AxiosResponse<DeleteOrder200>>(
    deleteOrderBody: DeleteOrderBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v2/marketplace/orders`,{data:
      deleteOrderBody, ...options}
    );
  }

/**
 * Updates and returns the order nonce for a user on a specific chain.
 */
export const updateOrderNonce = <TData = AxiosResponse<UpdateOrderNonce200>>(
    updateOrderNonceRequest: UpdateOrderNonceRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/marketplace/order-nonce`,
      updateOrderNonceRequest,options
    );
  }

/**
 * Validates an order and marks it as invalid if validation fails.
 */
export const validateOrder = <TData = AxiosResponse<ValidateOrder200>>(
    validateOrderRequest: ValidateOrderRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/marketplace/orders/validate`,
      validateOrderRequest,options
    );
  }

/**
 * Create a new hyperboard. Creates the collections passed to it automatically.
 */
export const createHyperboard = <TData = AxiosResponse<HyperboardResponse>>(
    hyperboardCreateRequest: HyperboardCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/hyperboards`,
      hyperboardCreateRequest,options
    );
  }

export const updateHyperboard = <TData = AxiosResponse<HyperboardResponse>>(
    hyperboardId: string,
    hyperboardUpdateRequest: HyperboardUpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/v2/hyperboards/${hyperboardId}`,
      hyperboardUpdateRequest,options
    );
  }

export const deleteHyperboard = <TData = AxiosResponse<BaseResponse>>(
    hyperboardId: string,
    params: DeleteHyperboardParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v2/hyperboards/${hyperboardId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const createBlueprint = <TData = AxiosResponse<BlueprintResponse>>(
    blueprintCreateRequest: BlueprintCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/blueprints`,
      blueprintCreateRequest,options
    );
  }

export const deleteBlueprint = <TData = AxiosResponse<DeleteBlueprint200>>(
    blueprintId: number,
    blueprintDeleteRequest: BlueprintDeleteRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v2/blueprints/${blueprintId}`,{data:
      blueprintDeleteRequest, ...options}
    );
  }

export const mintBlueprint = <TData = AxiosResponse<BlueprintResponse>>(
    blueprintId: number,
    blueprintQueueMintRequest: BlueprintQueueMintRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/blueprints/mint/${blueprintId}`,
      blueprintQueueMintRequest,options
    );
  }

/**
 * Submits a new allowlist for validation and storage on IPFS. While we maintain a database of allowlists, the allowlist itself is stored on IPFS.
Try to keep a backup of the allowlist for recovery purposes.

Provide the dump of the OpenZeppelin MerkleTree and the total units.
 */
export const storeAllowList = <TData = AxiosResponse<StorageResponse>>(
    storeAllowListRequest: StoreAllowListRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/allowlists`,
      storeAllowListRequest,options
    );
  }

/**
 * Submits a new allowlist for validation.

Provide the dump of the OpenZeppelin MerkleTree and the total units.
 */
export const validateAllowList = <TData = AxiosResponse<ValidationResponse>>(
    validateAllowListRequest: ValidateAllowListRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v2/allowlists/validate`,
      validateAllowListRequest,options
    );
  }

export type AddOrUpdateUserResult = AxiosResponse<UserResponse>
export type UploadResult = AxiosResponse<UploadResponse>
export type CancelSignatureRequestResult = AxiosResponse<CancelSignatureRequest200>
export type ProcessSignatureRequestsResult = AxiosResponse<ProcessSignatureRequests200>
export type HealthCheckResult = AxiosResponse<HealthCheck200>
export type StoreMetadataResult = AxiosResponse<StoreMetadata201>
export type StoreMetadataWithAllowlistResult = AxiosResponse<StorageResponse>
export type ValidateMetadataResult = AxiosResponse<ValidationResponse>
export type ValidateMetadataWithAllowlistResult = AxiosResponse<ValidationResponse>
export type StoreOrderResult = AxiosResponse<StoreOrder201>
export type DeleteOrderResult = AxiosResponse<DeleteOrder200>
export type UpdateOrderNonceResult = AxiosResponse<UpdateOrderNonce200>
export type ValidateOrderResult = AxiosResponse<ValidateOrder200>
export type CreateHyperboardResult = AxiosResponse<HyperboardResponse>
export type UpdateHyperboardResult = AxiosResponse<HyperboardResponse>
export type DeleteHyperboardResult = AxiosResponse<BaseResponse>
export type CreateBlueprintResult = AxiosResponse<BlueprintResponse>
export type DeleteBlueprintResult = AxiosResponse<DeleteBlueprint200>
export type MintBlueprintResult = AxiosResponse<BlueprintResponse>
export type StoreAllowListResult = AxiosResponse<StorageResponse>
export type ValidateAllowListResult = AxiosResponse<ValidationResponse>
